# Generated by Django 4.0.5 on 2022-07-04 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_desc_post_descr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='descr',
            new_name='desc',
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='static'),
        ),
    ]
